### ISSUE TITLE
Swift 3 Migration

### ISSUE THREAD

**Issue by chris-pilcher** [raywenderlich/swift-algorithm-club#181]
# And... we're done!

Thanks everyone for pitching in!
____

Xcode 8 and Swift 3 will be formally released soon and we need to migrate everything to [Swift 3](https://www.raywenderlich.com/135655/whats-new-swift-3). 

Want to help out with the migration? Awesome! :] 
## Please follow this process for migrating to Swift 3
- Download the Xcode 8.X
- Create a pull request to "claim" an algorithm or data structure you'd like to migrate. Just so multiple people don't work on the same thing.
- Migrate the algorithm/data structure project, playground, tests and readme to Swift 3
  - Uncomment test project in [.travis.yml](https://github.com/raywenderlich/swift-algorithm-club/blob/master/.travis.yml) so it will run on our Xcode 8 Travis CI build server
- Comment in the pull request when the changes are ready to be merged

Suggestions and feedback is welcome!
## List of algorithms to be migrated to Swift 3

`nil`

## Completed Migrations
- [x] AVL Tree #183 
- [x] All-Pairs Shortest Paths #347
- [x] Array2D #189
- [x] B-Tree #203
- [x] Binary Search Tree 
- [x] Binary Search #184
- [x] Binary Tree #213
- [x] Bit Set #194 
- [x] Bloom Filter #195
- [x] Bounded Priority Queue #218 
- [x] Boyer-Moore #248 
- [x] Breadth-First #237
- [x] Brute-Force String Search #239
- [x] Bubble Sort (no code)
- [x] Bucket Sort #281 
- [x] Comb Sort #350 
- [x] Combinatorics #270 
- [x] Count Occurrences #201
- [x] Counting Sort #235
- [x] Depth-First Search #238
- [x] Deque #303
- [x] Fixed Size Array #271 
- [x] Fizz Buzz #229
- [x] GCD #219 
- [x] Graph #267
- [x] Hash Set #276
- [x] Hash Table #216
- [x] Heap Sort #334
- [x] Heap 3945383d306ac027f779461789d6b0deddca4348
- [x] Huffman Coding #344
- [x] Insertion Sort #198 
- [x] K-Means #349
- [x] Kth Largest Element #228
- [x] Linear Regression #283 
- [x] Linear Search #200
- [x] Linked List #250 
- [x] Longest Common Subsequence #243
- [x] Merge Sort #199
- [x] Minimum Edit Distance #302 
- [x] Minimum Spanning Tree (Unweighted) #345
- [x] Monty Hall Problem #241 
- [x] Ordered Array #232
- [x] Ordered Set #234
- [x] Palindromes #187
- [x] Priority Queue #233
- [x] Queue #197 
- [x] Quicksort #217 
- [x] Radix Sort #347 
- [x] Radix Tree #242 
- [x] Red-Black Tree #214 
- [x] Ring Buffer #265
- [x] Run-Length Encoding #364
- [x] Segment Tree #220 
- [x] Selection Sampling (no changes necessary)
- [x] Select Minimum Maximum #333 
- [x] Selection Sort
- [x] Set Cover (Unweighted) #366 
- [x] Shell Sort #260 
- [x] Shortest Path (Unweighted) #343
- [x] Shuffle #273 #274 
- [x] Shunting Yard #365 
- [x] Single-Source Shortest Paths (Weighted) #356 
- [x] Stack #196
- [x] Ternary Search Tree
- [x] Topological Sort #259
- [x] Treap #251 
- [x] Threaded Binary Tree #367
- [x] Tree #193
- [x] Trie #208 
- [x] Two-Sum Problem #266
- [x] Union-Find #192

**Comment by Jxrgxn** [comment]
I knew this day would come.

**Comment by lostatseajoshua** [comment]
@chris-pilcher Will the Swift 3 implementation override the current implementations? Can we add a folder for each algorithm to organize implementations into Swift 2 and Swift 3? They can share the same` README` for describing the algorithm.

#### Example of folder structure
```
- Merge Sort
  - Swift 2
    - Implementation.swift
  - Swift 3
   - Implementation.swift
  - README
```

**Comment by chris-pilcher** [comment]
@lostatseajoshua Thanks for the suggestion! I'm keen to have a single version because of the complexity associated with keeping multiple versions. Potential complications/difficulties I can think of:
- Keeping multiple versions of the same project/playground/tests in sync
- Future contributions would require multiple implementations
- Build server would have to handle multiple versions
- Handling future versions of Swift

Overall, I think it would be best to overwrite the current Swift 2 implementations.

**Comment by lostatseajoshua** [comment]
@chris-pilcher Great points! I agree with the difficulties one version will be better. With that point I am going to make a couple PRs to claim some algorithms in Swift 3 👍

**Comment by tuliot** [comment]
@kelvinlauKL Linked List was updated with #212 . Can you check it off the todo?

**Comment by JaapWijnen** [comment]
The Red-Black tree has been updated!

**Comment by JaapWijnen** [comment]
#232 updates Ordered Array to swift 3

**Comment by JaapWijnen** [comment]
#232 updates Priority Queue to swift 3

**Comment by JaapWijnen** [comment]
Red-Black tree can be checked on the list since #214

**Comment by ivanicspeter92** [comment]
#250 Linked List

**Comment by goingreen** [comment]
#251 Treap

**Comment by JaapWijnen** [comment]
Oh sorry didnt see #259 and did similar work in #264

**Comment by shashank3369** [comment]
Hello @chris-pilcher, I was wondering if the ones that don't have check marks are the ones that still need to be migrated. If so I would be happy to help.

**Comment by kelvinlauKL** [comment]
yep @shashank3369, you're correct.

**Comment by mattThousand** [comment]
#334 Heap Sort

**Comment by grosch** [comment]
I'm not familiar enough with github to know how to properly do the pull/push requests, but here's how I'd rewrite the "Comb Sort" algorithm.  That 'while' loop that was in there confused the heck out of me.  I think this one is much cleaner.

```Swift
func combSort(input: [Int]) -> [Int] {
    let shrink = 1.3

    var copy = input
    var gap = copy.count

    while gap > 1 {
        gap = max(1, Int(Double(gap) / shrink))

        for i in 0 ..< copy.count - gap {
            if copy[i] > copy[i + gap] {
                swap(&copy[i], &copy[i + gap])
            }
        }
    }

    return copy
}
```

**Comment by gonini** [comment]
#343 Shortest Path (Unweighted)

**Comment by gonini** [comment]
#345 Minimum Spanning Tree (Unweighted Graph)

**Comment by pbodsk** [comment]
#344 Huffman Coding

**Comment by pbodsk** [comment]
#347 All-Pairs Shortest Paths

**Comment by taiheng** [comment]
#349 K-Means

**Comment by taiheng** [comment]
#350 Combsort, adding tests.

**Comment by pbodsk** [comment]
#352 Ternary Search Tree

**Comment by taiheng** [comment]
#353 Radix Sort

**Comment by pbodsk** [comment]
All-Pairs Shortest Pairs has been upgraded and merged too (PR #347), so that should be checked of as well, can I do that myself?

**Comment by kelvinlauKL** [comment]
Thanks @pbodsk, updated.

**Comment by pbodsk** [comment]
#356 Single-Source Shortest Paths

**Comment by magonicolas** [comment]
Hi, this has been migrated to swift 3, But I can't use it, any help would be awesome. I Open the project and it gives me a lot of errors. I also open de playground, and it says : No such module 'Graph'. How Can I solve it?

**Comment by vincentngo** [comment]
@magonicolas you need to first build the Graph and SSSP projects. The playground will work after that. Let me know if that doesn't work.

**Comment by magonicolas** [comment]
Thanks for the fast answer @vincentngo  but it still gives me the same error. Felling dumb right now, don't know how to make this work.

**Comment by magonicolas** [comment]
@vincentngo I make it work opening SSSP.xcworkspace, but not the playground. Thanks for your help. This algorithm give me the shortest path to pass over all nodes. How Can I just have the shortest math from one point to another? (Not passing from all nodes.)

**Comment by vincentngo** [comment]
@magonicolas not sure i follow, btw could you please post the questions on the forum. This thread is only for swift 3 migration. Thanks!

**Comment by naeemshaikh90** [comment]
#270 Combinatorics is migrated to swift 3?

**Comment by naeemshaikh90** [comment]
What do we need to migrate in Images? 😀

**Comment by kelvinlauKL** [comment]
@naeemshaikh90 Good point, also marked combinatorics as migrated. Thanks 👍

**Comment by JaapWijnen** [comment]
@kelvinlauKL Just checked, I think Selection Sampling is already written in swift 3. Compiles just fine on my mac.

**Comment by kelvinlauKL** [comment]
@JaapWijnen Thanks for the heads up.

**Comment by JaapWijnen** [comment]
#364 Running Length Encoding migrated to Swift 3

**Comment by JaapWijnen** [comment]
#365 Shunting Yard migrated to Swift 3

**Comment by JaapWijnen** [comment]
#366 Set Cover (unweighted) migrated to Swift 3

**Comment by JaapWijnen** [comment]
And the last one! #367

**Comment by kelvinlauKL** [comment]
Wow @JaapWijnen, you're on a roll 👍 

I'll review those later, but for now it seems like we're finally done.

Thanks everyone!
